os: osx
osx_image: xcode9.3
script:
  - xcodebuild -version
  - carthage version
  - swiftlint version
  - echo 'Bootstrap' && echo -en 'travis_fold:start:Bootstrap\\r'
  - "./bootstrap.sh"
  - echo -en 'travis_fold:start:Bootstrap\\r'
  - set -o pipefail && env "NSUnbufferedIO=YES" xcodebuild test -scheme WWDC -project WWDC.xcodeproj | xcpretty -f `xcpretty-travis-formatter`
