os: osx
osx_image: xcode9.3
script:
  - xcodebuild -version
  - carthage version
  - swiftlint version
  - echo 'travis_fold:start:bootstrap\033[33;1mBootstrap\033[0m\n'
  - "./bootstrap.sh"
  - echo 'travis_fold:end:bootstrap\n'
  - set -o pipefail && env "NSUnbufferedIO=YES" xcodebuild test -scheme WWDC -project WWDC.xcodeproj | xcpretty -f `xcpretty-travis-formatter`
